#!/bin/bash

PRE="gs://needle-files/"

modified_args=()

if [ "$#" -eq 0 ]; then
    modified_args+=("${PRE}")
else
  for arg in "$@"; do
    modified_args+=("${PRE}${arg}")
  done
fi

gcloud storage ls ${modified_args[@]}
