#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <module_id> <faa_dir>" >&2
  exit 1
fi

module_id="$(printf "%s" "$1" | tr '[:upper:]' '[:lower:]')"
faa_dir=$2
output_dir="data/${module_id}_results/alignments"
mkdir -p $output_dir

rm -f $output_dir/*.faa
rm -f $output_dir/*.png

if [[ ! -d "$faa_dir" ]]; then
  echo "Directory not found: $faa_dir" >&2
  exit 1
fi

for faa_path in "$faa_dir"/*.faa; do
  [ -e "$faa_path" ] || continue

  filename=$(basename -- "$faa_path")
  stem="${filename%.*}"
  hmm="${filename%%[_-]*}"

  hmm_path="${output_dir}/$hmm.hmm"
  aln_path="${output_dir}/$stem.faa"
  png_path="${output_dir}/$stem.png"
  # echo $hmm_path
  echo $aln_path

  hmmfetch data/${module_id}_ko.hmm $hmm > $hmm_path
  hmmalign --outformat A2M --trim $hmm_path $faa_path > $aln_path
  # hmmalign does not create uniform length alignments that pymsavis requires
  # scripts/align/mk-msa-vis $aln_path $png_path
  rm $hmm_path
done
