#!/bin/bash

# arguments, in order:
#   - module ID (i.e. mNNN)
#   - ko ID (i.e. Kxxx)

mkdir -p data/$1_results/alignments
hmmalign --outformat afa kegg-downloads/profiles/$2.hmm data/$1_results/faa/$2.faa > data/$1_results/alignments/$2-hmmalign.faa
