#!/bin/bash

# argument: module id, genome accession list file name

module=$1

# Loop through each line of the file
while IFS= read -r acc; do

outfn="data/${module}_results/classify.tsv"
PYTHONPATH=. python3 scripts/classify/classify.py --cpu 2                      --disable-cutoff-ga --genome-accession $acc data/${module}_ko.hmm ${module} ${outfn}
PYTHONPATH=. python3 scripts/classify/classify.py --cpu 2 --filter-by ${outfn} --disable-cutoff-ga --genome-accession $acc kegg-downloads/ko.hmm ${module} ${outfn}

done < $2
