#!/bin/bash

# argument: module id, genome accession list file name

module=$1
outfn="data/${module}_results/classify.tsv"

# Loop through each line of the file
while IFS= read -r acc; do

tmpfn="data/${module}_results/classify_${acc}.$$"
PYTHONPATH=. python3 scripts/classify/classify.py --cpu 2                      --disable-cutoff-ga --genome-accession $acc data/${module}_ko.hmm ${module} ${tmpfn}
PYTHONPATH=. python3 scripts/classify/classify.py --cpu 2 --filter-by ${tmpfn} --disable-cutoff-ga --genome-accession $acc kegg-downloads/ko.hmm ${module} ${outfn}
rm ${tmpfn}

done < $2
