#!/bin/bash

# argument: genome accession list file name

# Loop through each line of the file
while IFS= read -r acc; do

PYTHONPATH=. python3 scripts/classify/classify.py --disable-cutoff-ga --genome-accession $acc data/m00009_ko.hmm m00009
PYTHONPATH=. python3 scripts/classify/classify.py --filter-by-prev-output --genome-accession $acc pfam-downloads/Pfam-A.hmm m00009

done < $1
